import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ position: "relative", minHeight: "100vh" }}>
        <Navbar />
        <main>{children}</main>
        <Footer style={{ position: "fixed", width: "100%", marginBottom: "0" }} />
      </body>
    </html>
  );
}
